steps:


- id: &BUILD Build Image
  name: 'hashicorp/packer:latest'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","source_image_family=${_SOURCE_IMAGE_FAMILY}",
        "-var","source_image_project=${_SOURCE_IMAGE_PROJECT}",
        "-var","subnet=${_SUBNETWORK}",
        "-var","image_name=${_IMAGE_NAME}",
        "-var","image_family=${_IMAGE_FAMILY}",
        "-var","install_root=${_INSTALL_ROOT}",
        "-var","slurm_root=${_SLURM_ROOT}",
        "-var","spack_cache_bucket=${_SPACK_CACHE_BUCKET}",
        'compilers/packer.json']
  waitFor: ["-"]


substitutions:
    _ZONE: 'us-central1-c'
    _SUBNETWORK: 'default'
    _SOURCE_IMAGE_FAMILY: 'schedmd-slurm-20-11-4-centos-7'
    _SOURCE_IMAGE_PROJECT: 'schedmd-slurm-public'
    _IMAGE_NAME: 'hpc-apps-gcp-dev'
    _IMAGE_FAMILY: 'hpc-apps-gcp'
    _INSTALL_ROOT: '/apps'
    _SLURM_ROOT: '/usr/local'
    _SPACK_CACHE_BUCKET: "gs://gcp-spack-cache.fluidnumerics.com"

timeout : 28800s
