steps:


- id: &BUILD Build Image
  name: 'hashicorp/packer:latest'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","source_image_family=${_SOURCE_IMAGE_FAMILY}",
        "-var","source_image_project=${_SOURCE_IMAGE_PROJECT}",
        "-var","subnet=${_SUBNETWORK}",
        "-var","image_name=${_IMAGE_NAME}",
        "-var","image_family=${_IMAGE_FAMILY}",
        "-var","install_root=${_INSTALL_ROOT}",
        "-var","slurm_root=${_SLURM_ROOT}",
        "-var","compiler=${_COMPILER}",
        "-var","pkg_path=${_PKG_PATH}",
        "-var","common_path=${_COMMON_PATH}",
        'singularity/packer.json']
  waitFor: ["-"]


substitutions:
    _ZONE: 'us-central1-c'
    _SUBNETWORK: 'default'
    _SOURCE_IMAGE_FAMILY: 'schedmd-slurm-20-11-4-centos-7'
    _SOURCE_IMAGE_PROJECT: 'schedmd-slurm-public'
    _IMAGE_NAME: 'singularity-fluid-gcp-latest'
    _IMAGE_FAMILY: 'singularity-fluid-gcp'
    _INSTALL_ROOT: '/apps'
    _SLURM_ROOT: '/usr/local'
    _COMPILER: 'gcc@10.2.0'
    _PKG_PATH: "singularity"
    _COMMON_PATH: "common"

timeout : 86400s
