steps:


- id: &BUILD Build Image
  name: 'hashicorp/packer:latest'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","source_image_family=${_SOURCE_IMAGE_FAMILY}",
        "-var","source_image_project=${_SOURCE_IMAGE_PROJECT}",
        "-var","subnet=${_SUBNETWORK}",
        "-var","image_name=tmp-${_IMAGE_NAME}",
        "-var","install_root=${_INSTALL_ROOT}",
        "-var","slurm_root=${_SLURM_ROOT}",
        "-var","compiler=${_COMPILER}",
        "-var","pkg_path=${_PKG_PATH}",
        "-var","common_path=${_COMMON_PATH}",
        '${_PKG_PATH}/packer.json']
  waitFor: ["-"]

- id: Add GuestOS Features
  name: "gcr.io/cloud-builders/gcloud"
  args: ["compute",
         "images",
         "create",
         "${_IMAGE_NAME}",
         "--family=${_IMAGE_FAMILY}",
         "--source-image=tmp-${_IMAGE_NAME}",
         "--source-image-project=${PROJECT_ID}",
         "--guest-os-features=GVNIC"]

- id: Remove temporary image
  name: "gcr.io/cloud-builders/gcloud"
  args: ["compute",
         "images",
         "delete",
         "tmp-${_IMAGE_NAME}"]

substitutions:
    _ZONE: 'us-central1-c'
    _SUBNETWORK: 'default'
    _SOURCE_IMAGE_FAMILY: 'schedmd-slurm-20-11-4-centos-7'
    _SOURCE_IMAGE_PROJECT: 'schedmd-slurm-public'
    _IMAGE_NAME: 'singularity-gcp-foss-latest'
    _IMAGE_FAMILY: 'singularity-gcp-foss'
    _INSTALL_ROOT: '/opt'
    _SLURM_ROOT: '/usr/local'
    _COMPILER: 'gcc@10.2.0'
    _PKG_PATH: "singularity"
    _COMMON_PATH: "common"

timeout : 86400s
